name: Docker Build & Push

on:
  push:
    branches:
      - main  # Change si nécessaire

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Get latest version
        id: version
        run: |
          # Pull existing image tags (optional, requires auth)
          docker pull elsal1/bon-app:latest || true
          
          # List tags and find latest version
          tags=$(curl -s https://hub.docker.com/v2/repositories/elsal1/bon-app/tags/?page_size=100 | jq -r '.results[].name')
          current_version=$(echo "$tags" | grep -E '^v[0-9]+$' | sed 's/v//' | sort -rn | head -n1)
          current_version=${current_version:-0}
          new_version=$((current_version + 1))
          echo "new_version=v$new_version" >> $GITHUB_OUTPUT

      - name: Build and push Docker images
        run: |
          docker build . --platform linux/amd64 \
            -t elsal1/bon-app:latest \
            -t elsal1/bon-app:${{ steps.version.outputs.new_version }}

          docker push elsal1/bon-app:latest
          docker push elsal1/bon-app:${{ steps.version.outputs.new_version }}
